node {
    def server = Artifactory.server 'JFROG_INSTANCE'
    def rtNuget = Artifactory.newNugetBuild()
    def buildInfo

    stage ('Clone') {
        git url: '<git url>'
    }

    stage ('Artifactory configuration') {
        rtNuget.resolver repo: '<artifactory repository>', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('NuGet restore') {
        rtNuget.run buildInfo: buildInfo, args: 'restore'
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}