node {
    def server = Artifactory.server 'JFROG_INSTANCE'
    def rtNpm = Artifactory.newNpmBuild()
    def buildInfo

    stage ('Clone') {
        git url: '<git url>'
    }

    stage ('Artifactory configuration') {
        rtNpm.deployer repo: '<artifactory repository>', server: server
        rtNpm.resolver repo: '<artifactory repository>', server: server
        // Tool name from Jenkins configuration
        rtNpm.tool = 'NPM_TOOL'
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Install npm') {
        rtNpm.install buildInfo: buildInfo
    }

    stage ('Publish npm') {
        rtNpm.publish buildInfo: buildInfo
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}