node {
    def server = Artifactory.server 'JFROG_INSTANCE'
    def rtDotnet = Artifactory.newDotnetBuild()
    def buildInfo

    stage ('Clone') {
        git url: '<git url>'
    }

    stage ('Artifactory configuration') {
        rtDotnet.resolver repo: '<artifactory repository>', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('.NET restore') {
        rtDotnet.run buildInfo: buildInfo, args: 'restore'
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}