resources:
  - name: git-resource
    type: GitRepo
    configuration:
      path: <GIT_ORG_AND_REPO>
      gitProvider: <<JFROG_PIPELINES_GIT_INTEGRATION>>
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: build-info-resource
    type: BuildInfo
    configuration:
      sourceArtifactory: <JFROG_PIPELINES_ARTIFACTORY_INTEGRATION>
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: <jfrog pipelines pipeline name>
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: NpmBuild
        configuration:
          resolverRepo: <ARTIFACTORY_REPOSITORY>
          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: <JFROG_PIPELINES_ARTIFACTORY_INTEGRATION>
          inputResources:
            - name: git-resource
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: Build
        type: NpmBuild
        configuration:
          resolverRepo: <ARTIFACTORY_REPOSITORY>
          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: <<JFROG_PIPELINES_GIT_INTEGRATION>>
          inputResources:
            - name: git-resource
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: git-resource
          outputResources:
            - name: build-info-resource
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status git-resource
