node {
    def server = Artifactory.server 'JFROG_INSTANCE'
    def rtGo = Artifactory.newGoBuild()
    def buildInfo

    stage ('Clone') {
        git url: '<git url>'
    }

    stage ('Artifactory configuration') {
        rtGo.deployer repo: '<artifactory repository>', server: server
        rtGo.resolver repo: '<artifactory repository>', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Go run') {
        rtGo.run buildInfo: buildInfo, args: 'build'
    }

    stage ('Go publish') {
        rtGo.publish buildInfo: buildInfo, version: '1.0.0'
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}