node {
    def server
    def rtGradle = Artifactory.newGradleBuild()
    def buildInfo = Artifactory.newBuildInfo()

    stage ('Clone') {
        git url: '<git url>'
    }

    stage ('Artifactory configuration') {
        // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
        server = Artifactory.server 'JFROG_INSTANCE'

        // Tool name from Jenkins configuration
        rtGradle.tool = 'GRADLE_TOOL'
        rtGradle.deployer repo: '<artifactory repository>', server: server
        rtGradle.resolver repo: '<artifactory repository>', server: server
    }

    stage ('Exec Gradle') {
        rtGradle.run buildFile: 'build.gradle', tasks: 'artifactoryPublish', buildInfo: buildInfo
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}